os:
- osx
osx_image: xcode7.3
language: node_js
node_js:
- '0.12'
- '4'
- '5'
cache:
- apt
- directories:
  - "$HOME/.electron"
addons:
  apt:
    packages:
    - wine
before_install:
- |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      for pkg in `brew deps --skip-optional wine`; do
        brew install --ignore-dependencies --force-bottle $pkg
      done
      brew install --ignore-dependencies --force-bottle wine
    fi
after_success: npm run coveralls
env:
  global:
    # coveralls token
    secure: hG3cs8/tOGTa8IPewVuahcp1f8gwsk/rX7ReUBPag6cdZdJpkbjzxp8R97mhhCrFOP/fvX8zAbCelXvvhME/mjZTFgzSNHLBL/SJreHP5m2B1yxXkroiQFu1qwewvzzKmfcs5W1CD8J8WbJuBk9zozDQG9c1OxTaK87tBGh1xik=
